eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: courts
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/courts/**
        - id: players
          uri: lb://players
          predicates:
            - Path=/api/v1/players/**
        - id: friendships
          uri: lb://friendships
          predicates:
            - Path=/api/v1/friendships/**
management:
  tracing:
    sampling:
      probability: 1.0